<a href="https://colab.research.google.com/github/hizieun/ToTheTransformer/blob/main/_01_numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 모듈과 패키지

In [ ]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
# 패키지는 여러 모듈을 묶은 것 (폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [ ]:
import math # math라는 모듈이 있어요
print(math.pi)
print(math.sqrt(4)) # sqrt는 제곱근 구해줌

3.141592653589793
2.0


In [ ]:
import math as m # math를 가져오는 데 m 이라는 이름으로 가져온다
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import pi, sqrt
print(pi) # math.pi 는 오히려 안됨
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import * # * 이 all 이란 뜻
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [ ]:
from math import sqrt as s
print(s(4))

2.0


In [ ]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [ ]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [ ]:
import numpy as np # numpy는 라이브러리(패키지와 모듈들을 모아놓음)다 (numerical python)
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
import numpy.random
numpy.random.randn(3,3) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

array([[-0.42190351,  0.2104023 ,  1.60006693],
       [ 1.96590546, -0.14412101, -0.15346252],
       [ 0.74711708, -0.59222681,  0.10577433]])

In [ ]:
import numpy.random as nr
nr.randn(3,3)

array([[-1.08185828, -0.54107807, -0.22448597],
       [-0.63007591, -0.99228989,  0.09870555],
       [-0.00872154,  0.34490435, -1.2803823 ]])

In [ ]:
from numpy.random import randn
randn(3,3)

array([[-0.96745776,  0.51711404, -1.21881662],
       [ 0.91520634,  0.51469904, -0.48321608],
       [-1.22023073, -0.55610803,  0.30831105]])

In [ ]:
from numpy.random import *
rand(3,3) # uniform distribution

array([[0.70950847, 0.39287078, 0.75315234],
       [0.0553244 , 0.25149038, 0.0981763 ],
       [0.57329909, 0.08836524, 0.76165659]])

In [ ]:
from numpy.random import randn as rn
rn(3,3)

array([[-0.94486515,  1.53387261,  1.76079934],
       [-0.13009895,  0.61937373,  1.37758513],
       [ 0.6810059 ,  0.94612552,  0.28152648]])

In [ ]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[-2.71425024 -1.74778534  0.21040121]
 [-0.3294365   0.70869909  0.20277521]
 [ 0.75293556  1.41181707  0.36908543]]
[[0.94289868 0.31439648 0.20316251]
 [0.4551602  0.17243656 0.84328242]
 [0.05683198 0.68068606 0.86783174]]


## numpy 본격적으로

In [ ]:
import numpy as np
a=np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=np.array([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64
[1.  2.  3.1 4. ]


In [ ]:
A=np.array([[1,2,3],[3,4,5]]) # 이 셀부터는 import numpy as np 는 실행 했다 치고 작성
# A=np.array([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의 수

[[1 2 3]
 [3 4 5]]
(2, 3)
2
6


In [ ]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros((3,3))) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0 에서부터 1 포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!

[5 7 9]


In [ ]:
A=np.array([[1,2,3],[1,2,3]])
B=np.array([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## numpy 의 인덱싱과 슬라이싱

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
[4 5 6]
[4 6]
[3 6 9]


In [ ]:
# 3차원 행렬 인덱싱
A=np.array([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape)
print(A[0,1,2])

a=np.array([[[1,2,3,4]]]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6
(1, 1, 4)


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A>3] = 100
print(A) # 그러면 이런 것도 가능하다! (3보다 큰 애들을 100으로 바꿔줘)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=np.array([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2   3 100]
 [100   3 100   3]]
[[1 2]
 [7 8]]
[1 2]


In [ ]:
# array로 인덱싱
a=np.array([1,2,3,4,5])
A=a[2]
print(A)
A=a[ np.array(2) ] # np.array를 안에다가?
print(A)
A=a[ np.array([2,3,4]) ]
print(A)
A=a[ np.array([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=np.array([[1,2,3],[4,5,6]])
print(a[0])
A=a[ np.array([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = array([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

3
3
[3 4 5]
[[3 3 3]
 [4 4 4]]
[1 2 3]
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [4 5 6]]]


In [ ]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ array(bool) ] => A와 같은 shape을 가지는 array형 bool이 어디에 True를 가지고 있냐
print(A[ np.array([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ array ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ np.array([1,1,2,2,2]) ])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
[2]
[2]
[2]
[[3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]


## numpy의 여러 함수들

In [ ]:
A=np.random.randn(3,3) # 여긴 튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
print(B)

[[ 0.52293744  2.0798938   0.04136108]
 [ 0.06098918 -0.0204582   0.09214182]
 [ 1.79887679 -2.23479911  0.46520311]]
[[0.09621506 0.09752978 0.03738173]
 [0.95489653 0.72579904 0.89345078]
 [0.81040643 0.03143096 0.53075659]]


In [ ]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) = e^1
print(np.log10(10))
print(np.log2(2))
print(np.round(A)) # 반올림
print(np.round(A,2)) # 소수점 둘째자리까지
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[-1.23701962 -1.33580557 -1.37767659]
 [ 0.27661551  0.60017173 -0.27052217]
 [-0.795129   -0.59891433  0.34782616]]
[[1.23701962 1.33580557 1.37767659]
 [0.27661551 0.60017173 0.27052217]
 [0.795129   0.59891433 0.34782616]]
[[1.11221384 1.15577055 1.17374469]
 [0.52594249 0.77470751 0.52011746]
 [0.89170006 0.77389556 0.58976789]]
[[0.29024798 0.26294627 0.25216375]
 [1.31865926 1.82243174 0.76298099]
 [0.45152299 0.54940779 1.41598608]]
[[ 0.21270495  0.28953453  0.32039845]
 [-1.2851268  -0.51053945 -1.30740123]
 [-0.22925092 -0.51263671 -1.05605245]]
1.0
1.0
1.0
[[-1. -1. -1.]
 [ 0.  1. -0.]
 [-1. -1.  0.]]
[[-1.24 -1.34 -1.38]
 [ 0.28  0.6  -0.27]
 [-0.8  -0.6   0.35]]
[[-2. -2. -2.]
 [ 0.  0. -1.]
 [-1. -1.  0.]]
[[-1. -1. -1.]
 [ 1.  1. -0.]
 [-0. -0.  1.]]


In [ ]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [ ]:
np.nan # not a number
# np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [ ]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
print(np.max(A,axis=1)) # 1D array로 바꿔버림
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(np.min(A))
print(np.min(A,axis=0))
print(np.min(A,axis=1))
print(np.argmax(A))
print(np.argmax(A,axis=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

[[ 1.29214842  0.87718244 -0.20902648  1.26800045]
 [ 0.10108548  0.52806244 -1.36363564 -1.46836196]
 [ 0.30768777 -0.25467179 -1.05957695 -0.09577414]]
1.2921484178361748
[ 1.29214842  0.87718244 -0.20902648  1.26800045]
[1.29214842 0.52806244 0.30768777]
[[ 1.29214842  0.87718244 -0.20902648  1.26800045]]
[[1.29214842]
 [0.52806244]
 [0.30768777]]
-1.468361962619482
[ 0.10108548 -0.25467179 -1.36363564 -1.46836196]
[-0.20902648 -1.46836196 -1.05957695]
0
[0 0 0 0]
[0 1 0]


In [ ]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

a=np.random.randn(6,1)
print(a)
print(a.sort(axis=0))

print(np.max(a))
print(a.max())

[[ 0.54542572]
 [-0.40966736]
 [-0.35351721]
 [-0.36290879]
 [-0.30240458]
 [ 0.8474323 ]]
[[-0.40966736]
 [-0.36290879]
 [-0.35351721]
 [-0.30240458]
 [ 0.54542572]
 [ 0.8474323 ]]
[[ 0.8474323 ]
 [ 0.54542572]
 [-0.30240458]
 [-0.35351721]
 [-0.36290879]
 [-0.40966736]]
[[-1.24138692]
 [-1.05585054]
 [-0.10866932]
 [-0.02571589]
 [-1.94189935]
 [-0.95130964]]
None
-0.025715891429294088
-0.025715891429294088


In [ ]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1,keepdims=True))
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True))
print(np.std(A)) # standard deviation 표준 편차

print(A.sum(axis=1, keepdims=True))
print(A.mean(axis=1, keepdims=True))
print(A.std())

[[ 0.21480807 -1.09355029 -0.10473369  1.56106927]
 [-0.02912846 -0.59322568 -0.24902594  0.21013641]
 [-1.07140889 -1.01379903 -0.5921068  -1.55532658]]
-4.316291620154645
[ 0.57759336 -0.66124368 -4.23264131]
[[ 0.57759336]
 [-0.66124368]
 [-4.23264131]]
-0.3596909683462204
[ 0.14439834 -0.16531092 -1.05816033]
[[ 0.14439834]
 [-0.16531092]
 [-1.05816033]]
0.7927611641372063
[[ 0.57759336]
 [-0.66124368]
 [-4.23264131]]
[[ 0.14439834]
 [-0.16531092]
 [-1.05816033]]
0.7927611641372063


In [ ]:
A=np.random.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

[2 1 1 2 2 3 4 1 3 3 2 4]
(12,)
[[[2 1 1]
  [2 2 3]]

 [[4 1 3]
  [3 2 4]]]
3


In [ ]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(np.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A=np.random.randn(4,3,6)
print(A.transpose(0,2,1).shape)

9
[[9]]
[[9]]
(4, 6, 3)


In [ ]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [ ]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [ ]:
A=np.ones((3,4))
B=np.zeros((3,4))
C=np.vstack([A,B])
D=np.hstack([A,B])
E=np.block([[A],[B]])
F=np.block([A,B])
G=np.block([ [[A]], [[B]] ])

print(C)
print(D)
print(E)
print(F)
print(G)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
A = np.random.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,4,5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [ ]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...] # np.newaxis is None <- True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape)
A2 = np.expand_dims(A,axis=2)
print(A2.shape)
A3 = np.expand_dims(A,axis=1)
print(A3.shape)
A1 = A.reshape(1,3,4)
print(A1.shape)
A2 = A.reshape(3,4,1)
print(A2.shape)
A3 = A.reshape(3,1,4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
